WebApp/ViewModels/Vehicles/VehicleCreateEditFromTransportOfferViewModel.cs
using System;

namespace WebApp.ViewModels.Vehicles
{
    /// <summary>
    /// ViewModel for editing Vehicle from transportOffer
    /// </summary>
    public class VehicleCreateEditFromTransportOfferViewModel: VehicleCreateEditViewModel
    {
        /// <summary>
        /// TransportOfferId
        /// </summary>
        public Guid TransportOfferId { get; set; }
    }
}

WebApp/ViewModels/Vehicles/VehicleCreateEditViewModel.cs
using BLL.App.DTO;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace WebApp.ViewModels.Vehicles
{
    /// <summary>
    /// Vehicles create and edit viewmodel
    /// </summary>
    public class VehicleCreateEditViewModel
    {
        /// <summary>
        /// BLL.App.DTO.Vehicle
        /// </summary>
        public Vehicle Vehicle { get; set; } = default!;

        /// <summary>
        /// SelectList for Vehicle
        /// </summary>
        public SelectList? VehicleTypeSelectList { get; set; }
    }
}

WebApp/ViewModels/Vehicles/VehicleSelectExistingOrNewViewModel.cs
using System;

namespace WebApp.ViewModels.Vehicles
{
    /// <summary>
    /// Viewmodel to select existing or new Vehicle 
    /// </summary>
    public class VehicleSelectExistingOrNewViewModel
    {
        /// <summary>
        /// TransportOfferId
        /// </summary>
        public Guid TransportOfferId { get; set; } = default!;
    }
}

WebApp/Controllers/TransportOffersController.cs
using System;
using System.Threading.Tasks;
using BLL.App.DTO;
using Contracts.BLL.App;
using Extensions.Base;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using WebApp.ViewModels.TransportOffers;

namespace WebApp.Controllers
{
    /// <summary>
    /// TransportOffers controller. 
    /// </summary>
    [Authorize]
    public class TransportOffersController : Controller
    {
        private readonly IAppBLL _bll;

        /// <summary>
        /// TransportOffers controller constructor.
        /// </summary>
        /// <param name="bll">IAppBLL</param>
        public TransportOffersController(IAppBLL bll)
        {
            _bll = bll;
        }

        // GET: TransportOffers
        /// <summary>
        /// Index View. Gets All TransportOffers.
        /// </summary>
        /// <returns>View with List of TransportOffers</returns>
        [AllowAnonymous]
        public async Task<IActionResult> Index()
        {
            var res = await _bll.TransportOffers.GetAllAsync();
            return View(res);
        }

        // GET: TransportOffers/Details/5
        /// <summary>
        /// Details view. Gets TransportOffer by id.
        /// </summary>
        /// <param name="id">GUID</param>
        /// <returns>View with TransportOffer object</returns>
        [AllowAnonymous]
        public async Task<IActionResult> Details(Guid? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var transportOffer = await _bll.TransportOffers.FirstOrDefaultAsync(id.Value);
            if (transportOffer == null)
            {
                return NotFound();
            }

            var vm = new TransportOfferDetailsViewModel();
            vm.TransportOffer = transportOffer;
            if (User.Identity?.IsAuthenticated ?? false)
            {
                vm.UserVehiclesCount = await _bll.Vehicles.GetUserVehiclesCount(User.GetUserId()!.Value);
                vm.UserTrailersCount = await _bll.Trailers.GetUserTrailerCount(User.GetUserId()!.Value);
            }
            
            return View(vm);
        }

        // GET: TransportOffers/Create
        /// <summary>
        /// Create view. Gets TransportMeta, Vehicle, Trailer and Organisations.
        /// </summary>
        /// <returns>View with TransportOfferCreateEditViewModel</returns>
        public async Task<IActionResult> Create(Guid? vehicleId, Guid? transportNeedId)
        {
            if (vehicleId == null)
            {
                return NotFound();
            }

            var vehicle = await _bll.Vehicles.FirstOrDefaultAsync(vehicleId.Value, User.GetUserId()!.Value);
            if (vehicle == null)
            {
                return NotFound();
            }

            var vm = new TransportOfferCreateEditViewModel();
            vm.VehicleId = vehicle.Id;
            if (transportNeedId != null)
            {
                vm.TransportNeedId = transportNeedId;
            }
            vm.WeightUnitSelectList =
                new SelectList(await _bll.Units.GetWeightUnits(), nameof(Unit.Id), nameof(Unit.UnitCode));
            return View(vm);
        }

        // POST: TransportOffers/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        /// <summary>
        /// Create view. Saves TransportOffer.
        /// </summary>
        /// <param name="vm">TransportOfferCreateEditViewModel</param>
        /// <returns>Redirects to index</returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(TransportOfferCreateEditViewModel vm)
        {
            if (ModelState.IsValid)
            {
                vm.TransportOffer.AppUserId = User.GetUserId()!.Value;
                var transportOffer = _bll.TransportOffers.Add(vm.VmToBll());
                await _bll.SaveChangesAsync();
                // If user wants to add Trailer to TransportOffer then Redirect to Trailers
                if (vm.UseTrailer!.Value)
                {
                    return RedirectToAction("TrailerFromSelectListForTransportOffer", "Trailers",
                        new {transportOfferId = transportOffer.Id, transportNeedId = vm.TransportNeedId});
                }
                // If TransportNeedId == null then its not from creating TransportOffer to TransportNeed
                if (vm.TransportNeedId == null)
                {
                    return RedirectToAction(nameof(Details), new {id = transportOffer.Id});
                }
                // If TransportNeedId != null then its  from creating TransportOffer to TransportNeed 
                return RedirectToAction("Create", "Transports",
                    new {transportNeedId = vm.TransportNeedId, transportOfferId = transportOffer.Id});
            }

            vm.WeightUnitSelectList = new SelectList(await _bll.Units.GetWeightUnits(), nameof(Unit.Id),
                nameof(Unit.UnitCode), vm.TransportOffer.UnitId);
            return View(vm);
        }

        /// <summary>
        /// 
        /// </summary>
        /// <returns></returns>
        public async Task<IActionResult> VehicleForTransportOffer(string? useprev, Guid? transportNeedId)
        {
            var vm = new TransportOfferVehicleViewModel();
            if (useprev != null)
            {
                vm.UsePreviousVehicle = useprev switch
                {
                    "true" => true,
                    "false" => false,
                    _ => vm.UsePreviousVehicle
                };
            }


            vm.HasPreviusVehicles = await _bll.Vehicles.HasVehicles(User.GetUserId()!.Value);
            // Add default to use previous vehicle - how many vehicles do people use anyway?
            if (vm.HasPreviusVehicles && useprev == null)
            {
                vm.UsePreviousVehicle = true;
            }

            if (transportNeedId != null)
            {
                vm.TransportNeedId = transportNeedId;
            }

            vm.VehicleSelectList = new SelectList(await _bll.Vehicles.GetAllAsync(User.GetUserId()!.Value),
                nameof(Vehicle.Id), nameof(Vehicle.Make));
            vm.VehicleVm.VehicleTypeSelectList = new SelectList(await _bll.VehicleTypes.GetAllAsync(),
                nameof(VehicleType.Id),
                nameof(VehicleType.VehicleTypeName));
            return View(vm);
        }

        /// <summary>
        /// Creates vehicle for Transportoffer
        /// </summary>
        /// <param name="vm">TransportOfferVehicleViewModel</param>
        /// <returns></returns>
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> VehicleForTransportOffer(TransportOfferVehicleViewModel vm)
        {
            if (ModelState.IsValid)
            {
                vm.VehicleVm.Vehicle.AppUserId = User.GetUserId()!.Value;
                var vehicle = _bll.Vehicles.Add(vm.VehicleVm.Vehicle);
                await _bll.SaveChangesAsync();
                // if transportneedID == null then this is usual transportoffer adding.
                // If vehicle is saved then redirect to TransportOfferCreate
                if (vm.TransportNeedId == null)
                {
                    return RedirectToAction(nameof(Create), new {vehicleId = vehicle.Id});
                }
                return RedirectToAction(nameof(Create), new {vehicleId = vehicle.Id, transportNeedId = vm.TransportNeedId});
            }

            vm.HasPreviusVehicles = await _bll.Vehicles.HasVehicles(User.GetUserId()!.Value);
            vm.VehicleVm.VehicleTypeSelectList = new SelectList(await _bll.VehicleTypes.GetAllAsync(),
                nameof(VehicleType.Id),
                nameof(VehicleType.VehicleTypeName), vm.VehicleVm.Vehicle.VehicleTypeId);
            vm.HasPreviusVehicles = await _bll.Vehicles.HasVehicles(User.GetUserId()!.Value);
            vm.VehicleSelectList = new SelectList(await _bll.Vehicles.GetAllAsync(User.GetUserId()!.Value),
                nameof(Vehicle.Id), nameof(Vehicle.Make));
            return View(vm);
        }

        /// <summary>
        /// ModifyAndAdd TransportOffer Vehicle - save or select new
        /// </summary>
        /// <param name="id">TransportOffer ID - GUID</param>
        /// <param name="useprev"></param>
        /// <returns></returns>
        public async Task<IActionResult> EditVehicleForTransportOffer(Guid id, string? useprev)
        {
            var transportOffer = await _bll.TransportOffers.FirstOrDefaultAsync(id, User.GetUserId()!.Value);
            if (transportOffer == null)
            {
                return NotFound();
            }

            var vm = new TransportOfferEditVehicleViewModel();
            vm.TransportOfferId = transportOffer.Id;
            if (useprev != null)
            {
                vm.UsePreviousVehicle = useprev switch
                {
                    "true" => true,
                    "false" => false,
                    _ => vm.UsePreviousVehicle
                };
            }

            var userVehicleCount = await _bll.Vehicles.GetUserVehiclesCount(User.GetUserId()!.Value);
            // TODO: If user has one vehicle, then there is no point to display selectList for vehicles
            vm.HasPreviusVehicles = userVehicleCount > 0;
            // Add default to use previous vehicle - how many vehicles do people use anyway?
            if (vm.HasPreviusVehicles && useprev == null && userVehicleCount > 1)
            {
                vm.UsePreviousVehicle = true;
            }

            vm.VehicleSelectList = new SelectList(await _bll.Vehicles.GetAllAsync(User.GetUserId()!.Value),
                nameof(Vehicle.Id), nameof(Vehicle.Make));

WebApp/Views/Vehicles/Create.cshtml
@using Base.Resources.WebApp
@model WebApp.ViewModels.Vehicles.VehicleCreateEditViewModel

@{
    ViewData["Title"] = WebAppUiCommon.Create;
}

<h1>@WebAppUiCommon.Create</h1>

<h4>@Resources.BLL.App.DTO.Vehicle._Vehicle</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            
            <partial name="_CreateEdit" model="Model"/>
            
            <div class="form-group">
                <input type="submit" value="@WebAppUiCommon.Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">@WebAppUiCommon.BackToList</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

WebApp/Views/Vehicles/Delete.cshtml
@using Base.Resources.WebApp
@model BLL.App.DTO.Vehicle

@{
    ViewData["Title"] = WebAppUiCommon.Delete;
}

<h1>@WebAppUiCommon.Delete</h1>

<h3>@WebAppUiCommon.DeleteConfirmation</h3>
<div>
    <h4>@Resources.BLL.App.DTO.Vehicle._Vehicle</h4>
    <hr />
   
    <partial name="_Details" model="Model"/>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="@WebAppUiCommon.Delete" class="btn btn-danger" /> |
        <a asp-action="Index">@WebAppUiCommon.BackToList</a>
    </form>
</div>

WebApp/Views/Vehicles/Details.cshtml
@using Base.Resources.WebApp
@model BLL.App.DTO.Vehicle

@{
    ViewData["Title"] = WebAppUiCommon.Details;
}

<h1>@WebAppUiCommon.Details</h1>

<div>
    <h4>@Resources.BLL.App.DTO.Vehicle._Vehicle</h4>
    <hr />
    
    <partial name="_Details" model="Model"/>
    
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">@WebAppUiCommon.Edit</a> |
    <a asp-action="Index">@WebAppUiCommon.BackToList</a>
</div>

WebApp/Views/Vehicles/Edit.cshtml
@using Base.Resources.WebApp
@model WebApp.ViewModels.Vehicles.VehicleCreateEditViewModel

@{
    ViewData["Title"] = WebAppUiCommon.Edit;
}

<h1>@WebAppUiCommon.Edit</h1>

<h4>@Resources.BLL.App.DTO.Vehicle._Vehicle</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
 
            <input type="hidden" asp-for="Vehicle.Id" />
            
            <partial name="_CreateEdit" model="Model"/>
            <div class="form-group">
                <input type="submit" value="@WebAppUiCommon.Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">@WebAppUiCommon.BackToList</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

WebApp/Views/Vehicles/EditFromTransportOffer.cshtml
@using Base.Resources.WebApp
@model WebApp.ViewModels.Vehicles.VehicleCreateEditFromTransportOfferViewModel


@{
    ViewData["Title"] = WebAppUiCommon.Edit;
}

<h1>@WebAppUiCommon.Edit</h1>

<h4>@Resources.BLL.App.DTO.Vehicle._Vehicle</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="EditFromTransportOffer">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
 
            <input type="hidden" asp-for="Vehicle.Id" />
            <input type="hidden" asp-for="TransportOfferId" />
            
            <partial name="_CreateEdit" model="Model"/>
            <div class="form-group">
                <input type="submit" value="@WebAppUiCommon.Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Details" asp-controller="TransportOffers" asp-route-id="@Model.TransportOfferId">@WebAppUiCommon.Cancel</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

WebApp/Views/Vehicles/Index.cshtml
@using Base.Resources.WebApp
@model IEnumerable<BLL.App.DTO.Vehicle>

@{
    ViewData["Title"] = Resources.BLL.App.DTO.Vehicle._Vehicles;
}

<h1>@Resources.BLL.App.DTO.Vehicle._Vehicles</h1>

<p>
    <a asp-action="Create">@WebAppUiCommon.CreateNew</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Make)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Model)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ReleaseDate)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.RegNr)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.VehicleType!.VehicleTypeName)
            </th>
            
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Make)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Model)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ReleaseDate)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.RegNr)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.VehicleType!.VehicleTypeName)
            </td>
            
            <td>
                <a asp-action="Edit" asp-route-id="@item.Id">@WebAppUiCommon.Edit</a> |
                <a asp-action="Details" asp-route-id="@item.Id">@WebAppUiCommon.Details</a> |
                <a asp-action="Delete" asp-route-id="@item.Id">@WebAppUiCommon.Delete</a>
            </td>
        </tr>
}
    </tbody>
</table>

WebApp/Views/Vehicles/_CreateEdit.cshtml
@using Base.Resources.WebApp
@model WebApp.ViewModels.Vehicles.VehicleCreateEditViewModel

<div class="form-group">
    <label asp-for="Vehicle.Make" class="control-label"></label>
    <input asp-for="Vehicle.Make" class="form-control"/>
    <span asp-validation-for="Vehicle.Make" class="text-danger"></span>
</div>
<div class="form-group">
    <label asp-for="Vehicle.Model" class="control-label"></label>
    <input asp-for="Vehicle.Model" class="form-control"/>
    <span asp-validation-for="Vehicle.Model" class="text-danger"></span>
</div>
<div class="form-group">
    <label asp-for="Vehicle.ReleaseDate" class="control-label"></label>
    <input asp-for="Vehicle.ReleaseDate" class="form-control"/>
    <span asp-validation-for="Vehicle.ReleaseDate" class="text-danger"></span>
</div>
<div class="form-group">
    <label asp-for="Vehicle.RegNr" class="control-label"></label>
    <input asp-for="Vehicle.RegNr" class="form-control"/>
    <span asp-validation-for="Vehicle.RegNr" class="text-danger"></span>
</div>
<div class="form-group">
    <label asp-for="Vehicle.VehicleTypeId" class="control-label"></label>
    <select asp-for="Vehicle.VehicleTypeId" class="form-control" asp-items="Model.VehicleTypeSelectList">
        <option>-- @WebAppUiCommon.PleaseSelect --</option>
    </select>
    <span asp-validation-for="Vehicle.VehicleTypeId" class="text-danger"></span>
</div>

WebApp/Views/Vehicles/_Details.cshtml
@model BLL.App.DTO.Vehicle

<dl class="row">
    <dt class = "col-sm-2">
        @Html.DisplayNameFor(model => model.Make)
    </dt>
    <dd class = "col-sm-10">
        @Html.DisplayFor(model => model.Make)
    </dd>
    <dt class = "col-sm-2">
        @Html.DisplayNameFor(model => model.Model)
    </dt>
    <dd class = "col-sm-10">
        @Html.DisplayFor(model => model.Model)
    </dd>
    <dt class = "col-sm-2">
        @Html.DisplayNameFor(model => model.ReleaseDate)
    </dt>
    <dd class = "col-sm-10">
        @Html.DisplayFor(model => model.ReleaseDate)
    </dd>
     <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.RegNr)
        </dt>
    <dd class = "col-sm-10">
        @Html.DisplayFor(model => model.RegNr)
    </dd>
    <dt class = "col-sm-2">
        @Html.DisplayNameFor(model => model.VehicleType)
    </dt>
    <dd class = "col-sm-10">
        @Html.DisplayFor(model => model.VehicleType!.VehicleTypeName)
    </dd>
</dl>